FROM blbltop-base:latest
ARG NPM_MIRROR
ARG COMMIT_HASH
# port args
ARG DEV_SEARCH_PORT
ARG SEARCH_PORT
ARG DEV_WEBSOCKET_PORT
ARG WEBSOCKET_PORT
ARG DEV_UI_PORT
ARG UI_PORT
# port envs
ENV SEARCH_PORT=$SEARCH_PORT
ENV WEBSOCKET_PORT=$WEBSOCKET_PORT
ENV UI_PORT=$UI_PORT
# Use stable version
RUN git clone https://gitee.com/Hansimov/bili-search-ui.git bili-search-ui
WORKDIR /app/bili-search-ui/quasar
RUN git checkout $COMMIT_HASH -f
# Replace port from dev to prod in `quasar.config.js`
RUN sed -i "s/${DEV_SEARCH_PORT}/${SEARCH_PORT}/g" quasar.config.js
RUN sed -i "s/${DEV_WEBSOCKET_PORT}/${WEBSOCKET_PORT}/g" quasar.config.js
RUN sed -i "s/${DEV_UI_PORT}/${UI_PORT}/g" quasar.config.js
# Replace port from dev to prod in `proxy.mjs`
RUN sed -i "s/${DEV_SEARCH_PORT}/${SEARCH_PORT}/g" proxy.mjs
RUN sed -i "s/${DEV_WEBSOCKET_PORT}/${WEBSOCKET_PORT}/g" proxy.mjs
# Install dependencies
RUN npm config set registry $NPM_MIRROR
RUN npm install
RUN quasar build
EXPOSE $UI_PORT
CMD quasar serve ./dist/spa --proxy proxy.mjs -p $UI_PORT --history
