FROM bili-search-base:latest
ARG NPM_MIRROR
ARG COMMIT_HASH
ARG PORT
RUN apt-get update && apt-get install -y curl
# Install node.js 18.x
#   - https://github.com/nodesource/distributions
RUN curl -fsSL https://deb.nodesource.com/setup_18.x -o ~/nodesource_setup.sh
RUN bash ~/nodesource_setup.sh
RUN apt-get install -y nodejs
# Use stable version
RUN git clone https://githubfast.com/Hansimov/bili-search-ui.git . && git checkout $COMMIT_HASH
WORKDIR /app/quasar
RUN npm config set registry $NPM_MIRROR
RUN npm i -g @quasar/cli
RUN npm install
EXPOSE $PORT
CMD ["quasar", "dev"]
