FROM bili-search-base:latest
ARG NPM_MIRROR
ARG COMMIT_HASH
ARG DEV_BACKEND_PORT
ARG BACKEND_PORT
ARG DEV_FRONTEND_PORT
ARG FRONTEND_PORT
ENV FRONTEND_PORT=$FRONTEND_PORT
# Use stable version
RUN git clone https://githubfast.com/Hansimov/bili-search-ui.git bili-search-ui
WORKDIR /app/bili-search-ui/quasar
RUN git checkout $COMMIT_HASH
# Replace dev port with production port
RUN sed -i "s/${DEV_BACKEND_PORT}/${BACKEND_PORT}/g" quasar.config.js
RUN sed -i "s/${DEV_FRONTEND_PORT}/${FRONTEND_PORT}/g" quasar.config.js
RUN sed -i "s/${DEV_BACKEND_PORT}/${BACKEND_PORT}/g" proxy.mjs
# Install dependencies
RUN npm config set registry $NPM_MIRROR
RUN npm install
RUN quasar build
EXPOSE $FRONTEND_PORT
CMD quasar serve ./dist/spa --proxy proxy.mjs -p $FRONTEND_PORT --history
