FROM ubuntu:jammy
WORKDIR /app
ARG UBUNTU_MIRROR
ARG NPM_MIRROR
# Replace sources list
#   - https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/
RUN echo "deb $UBUNTU_MIRROR jammy main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb $UBUNTU_MIRROR jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb $UBUNTU_MIRROR jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y git curl
# Install python and pip
RUN apt-get install -y python3 python3-pip
# Install node.js 18.x
#   - https://github.com/nodesource/distributions
RUN curl -fsSL https://deb.nodesource.com/setup_18.x -o ~/nodesource_setup.sh
RUN bash ~/nodesource_setup.sh
RUN apt-get -y install nodejs
# Install quasar
RUN npm config set registry $NPM_MIRROR
RUN npm i -g @quasar/cli