services:
  blbltop-base:
    build:
      context: .
      dockerfile: Dockerfile_base
      args:
        UBUNTU_MIRROR: http://mirrors.tuna.tsinghua.edu.cn/ubuntu/
        NPM_MIRROR: https://registry.npmmirror.com
    image: blbltop-base

  blbltop-backend:
    depends_on:
      - blbltop-base
    build:
      context: .
      dockerfile: Dockerfile_backend
      args:
        PIP_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
        COMMIT_HASH: 4c50f6439e7066185dc2135905fa7f54945d937e
    image: blbltop-backend
    network_mode: host
    volumes:
      - ../bili-search/configs/secrets.json:/app/bili-search/configs/secrets.json
      - ../bili-search/configs/elastic_ca.crt:/app/bili-search/configs/elastic_ca.crt

  blbltop-search:
    extends:
      service: blbltop-backend
    command: python3 -m apps.search_app -p 20001 -m prod

  blbltop-websocket:
    extends:
      service: blbltop-backend
    command: python3 -m apps.websocket_app -p 20003 -m prod

    depends_on:
      - bili-search-base
    build:
      context: .
      dockerfile: Dockerfile_frontend
      args:
        NPM_MIRROR: https://registry.npmmirror.com
        COMMIT_HASH: bd3eaefcfbe94f1551086e907b447de003f981c9
        DEV_BACKEND_PORT: 21001
        BACKEND_PORT: 20001
        DEV_FRONTEND_PORT: 21002
        FRONTEND_PORT: 20002
    image: bili-search-ui
    network_mode: host
# sudo usermod -aG docker $USER && newgrp docker
# docker compose up --build
