services:
  bili-search-base:
    build:
      context: .
      dockerfile: Dockerfile_base
      args:
        UBUNTU_MIRROR: http://mirrors.tuna.tsinghua.edu.cn/ubuntu/
        NPM_MIRROR: https://registry.npmmirror.com
    image: bili-search-base
  bili-seach-backend:
    depends_on:
      - bili-search-base
    build:
      context: .
      dockerfile: Dockerfile_backend
      args:
        PIP_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
        COMMIT_HASH: 21c35a4fb357812b4695860a97a970aa4c190c30
        BACKEND_PORT: 20001
    image: bili-search
    network_mode: host
    volumes:
      - ../bili-search/configs/secrets.json:/app/bili-search/configs/secrets.json
      - ../bili-search/configs/elastic_ca.crt:/app/bili-search/configs/elastic_ca.crt
  bili-seach-frontend:
    depends_on:
      - bili-search-base
    build:
      context: .
      dockerfile: Dockerfile_frontend
      args:
        NPM_MIRROR: https://registry.npmmirror.com
        COMMIT_HASH: 7bb6af43b9ce741ca603ee53d7eb84d7e02a7ac5
        DEV_BACKEND_PORT: 21001
        BACKEND_PORT: 20001
        DEV_FRONTEND_PORT: 21002
        FRONTEND_PORT: 20002
    image: bili-search-ui
    network_mode: host
# sudo usermod -aG docker $USER && newgrp docker
# docker compose up --build
