services:
  bili-search-base:
    build:
      context: .
      dockerfile: Dockerfile_base
      args:
        UBUNTU_MIRROR: http://mirrors.tuna.tsinghua.edu.cn/ubuntu/
    image: bili-search-base
  bili-seach-backend:
    depends_on:
      - bili-search-base
    build:
      context: .
      dockerfile: Dockerfile_backend
      args:
        PIP_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
        COMMIT_HASH: d8ea853
        BACKEND_PORT: 20001
    image: bili-search
    network_mode: host
    volumes:
      - ../bili-search/configs/secrets.json:/app/configs/secrets.json
      - ../bili-search/configs/elastic_ca.crt:/app/configs/elastic_ca.crt
  bili-seach-frontend:
    depends_on:
      - bili-search-base
    build:
      context: .
      dockerfile: Dockerfile_frontend
      args:
        NPM_MIRROR: https://registry.npmmirror.com
        COMMIT_HASH: c2c02ff
        DEV_BACKEND_PORT: 21001
        BACKEND_PORT: 20001
        DEV_FRONTEND_PORT: 21002
        FRONTEND_PORT: 20002
    image: bili-search-ui
    network_mode: host
# sudo usermod -aG docker $USER && newgrp docker
# docker compose up --build
