services:
  blbltop-base:
    build:
      context: .
      dockerfile: Dockerfile_base
      args:
        UBUNTU_MIRROR: http://mirrors.tuna.tsinghua.edu.cn/ubuntu/
        NPM_MIRROR: https://registry.npmmirror.com
    image: blbltop-base

  blbltop-backend:
    depends_on:
      - blbltop-base
    build:
      context: .
      dockerfile: Dockerfile_backend
      args:
        PIP_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
        COMMIT_HASH: 28ef3096fcf824d057fadbbcdb0e6d4103be87c2
    image: blbltop-backend
    network_mode: host
    volumes:
      - ../bili-search/configs/secrets.json:/app/bili-search/configs/secrets.json
      - ../bili-search/configs/elastic_ca.crt:/app/bili-search/configs/elastic_ca.crt

  blbltop-search:
    extends:
      service: blbltop-backend
    command: python3 -m apps.search_app -p 20001 -m prod

  blbltop-websocket:
    extends:
      service: blbltop-backend
    command: python3 -m apps.websocket_app -p 20003 -m prod

  blbltop-frontend:
    depends_on:
      - blbltop-base
    build:
      context: .
      dockerfile: Dockerfile_frontend
      args:
        NPM_MIRROR: https://registry.npmmirror.com
        COMMIT_HASH: 899d4d307abe53b108c59b6da35293d9361b059f
        DEV_SEARCH_PORT: 21001
        SEARCH_PORT: 20001
        DEV_WEBSOCKET_PORT: 21003
        WEBSOCKET_PORT: 20003
        DEV_UI_PORT: 21002
        UI_PORT: 20002
    image: blbltop-frontend
    network_mode: host
# sudo usermod -aG docker $USER && newgrp docker
# docker compose up --build
